### ISSUE TITLE
Create Your Portfolio

### ISSUE THREAD

**Issue by lawaniya-yash** [DecodersCommunity/portfolio_maker#1]

**Comment by parinitapatil** [comment]
Would it be possible for me to be assigned to this issue?

**Comment by AnkitVlekhak** [comment]
> Would it be possible for me to be assigned to this issue?

There is no need for that, you can fork this repo, make change and then put a PR here.

**Comment by prafull904434** [comment]
sir,
may i work with this issue,
can you assign to me

**Comment by lawaniya-yash** [comment]
> sir, may i work with this issue, can you assign to me
There is no need for that, you can fork this repo, make change and then put a PR here.

**Comment by lawaniya-yash** [comment]
> sir, may i work with this issue, can you assign to me

There is no need for that, you can fork this repo, make change and then put a PR here.

**Comment by prafull904434** [comment]
it shows permission denied so assign to me
