### ISSUE TITLE
change Background

### ISSUE THREAD

**Issue by lawaniya-yash** [DecodersCommunity/portfolio_maker#6]

**Comment by AdityaDhavale** [comment]
I would love to work on this issue , please assign me

**Comment by Kundanika04** [comment]
@lawaniya-yash Could you please assign this to me?

**Comment by lawaniya-yash** [comment]
> @lawaniya-yash I would love to work on this issue , please assign me

@AdityaDhavale just fork the repo and send pr , we will merge it.

**Comment by lawaniya-yash** [comment]
> @lawaniya-yash Could you please assign this to me?

@Kundanika04 just fork the repo and send pr , we will merge it.
